#!/bin/bash
clear
set -v

docker container run --rm -it \
    dockerfornovices/sqlite:0.1   $'create table t1  (c1 varchar(20));'

read x

docker container run --rm -it \
    dockerfornovices/sqlite:0.1   $'insert into t1 values (\'Hello\');'
