#!/bin/bash -v

cd work-dir

docker container run --rm -it \
    --workdir="/development" --user=$(id -u):$(id -g) -e HOME="/tmp/$(id -un)" \
    --mount type=bind,source=$PWD,target=/development \
    --mount type=volume,source=go-deps-my-project,target=/go \
    --publish 9089:8000 \
    --name myGoDev go-with-delve:1.14

