#!/bin/bash -v

docker container run --rm -it \
    --mount type=bind,source=$PWD,target=/development \
    --mount type=volume,source=go-deps-my-project,target=/go \
    --name myGoDev go-with-delve:1.14
