#!/bin/bash -v

VERSION=${1:-14}

docker image build --build-arg VERSION=$VERSION -t dockerfornovices/api-server:go-1.$VERSION .

#Tidy up. Not relevant to the demo

set +v
list=$(docker images -q -f "dangling=true" -f "label=autodelete=true")
if [ -n "$list" ]; then
     docker image rm $list  > /dev/null
fi

set -v

docker image list
